#!/usr/bin/env python3
"""
Embed Web Files into C++ Header
Converts HTML, CSS, and JavaScript files into C string constants
for embedding in ESP32 firmware.
"""

import os
import sys
from pathlib import Path
import gzip
import base64


def read_file(filepath):
    """Read file content."""
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()


def compress_content(content):
    """Compress content using gzip."""
    return gzip.compress(content.encode('utf-8'))


def generate_c_array(data, var_name):
    """Generate C array from binary data."""
    hex_str = ', '.join(f'0x{byte:02x}' for byte in data)
    lines = []
    lines.append(f'const uint8_t {var_name}[] PROGMEM = {{')

    # Split into lines of max 12 bytes for readability
    bytes_per_line = 12
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i+bytes_per_line]
        hex_chunk = ', '.join(f'0x{byte:02x}' for byte in chunk)
        lines.append(f'  {hex_chunk},')

    lines.append('};')
    lines.append(f'const size_t {var_name}_len = {len(data)};')
    return '\n'.join(lines)


def generate_header(files, output_path):
    """Generate C++ header file with embedded web assets."""
    header_lines = [
        '/**',
        ' * @file web_assets.h',
        ' * @brief Embedded web assets for MultiGeiger dashboard',
        ' * @note Auto-generated by tools/embed_web.py - DO NOT EDIT MANUALLY',
        ' */',
        '',
        '#pragma once',
        '',
        '#include <Arduino.h>',
        '',
        '// Compressed web assets (gzip)',
        ''
    ]

    # Process each file
    for file_info in files:
        filepath, var_prefix = file_info
        print(f'Processing: {filepath}')

        content = read_file(filepath)
        compressed = compress_content(content)

        print(f'  Original size: {len(content)} bytes')
        print(f'  Compressed size: {len(compressed)} bytes')
        print(f'  Compression ratio: {len(compressed)/len(content)*100:.1f}%')

        # Generate C array
        array_code = generate_c_array(compressed, f'{var_prefix}_gz')
        header_lines.append(f'// {os.path.basename(filepath)}')
        header_lines.append(array_code)
        header_lines.append('')

    # Add helper function
    header_lines.extend([
        '// Helper function to serve compressed content',
        'inline void serveCompressed(WebServer& server, const uint8_t* content,',
        '                            size_t len, const char* contentType) {',
        '  server.sendHeader("Content-Encoding", "gzip");',
        '  server.send_P(200, contentType, (const char*)content, len);',
        '}',
        ''
    ])

    # Write header file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(header_lines))

    print(f'\nGenerated: {output_path}')


def main():
    # Paths
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    web_dir = project_root / 'web'
    output_file = project_root / 'src' / 'comm' / 'wifi' / 'web_assets.h'

    # Files to embed
    files = [
        (web_dir / 'dashboard.html', 'dashboard_html'),
        (web_dir / 'style.css', 'style_css'),
        (web_dir / 'app.js', 'app_js'),
        (web_dir / 'config.html', 'config_html'),
        (web_dir / 'config-style.css', 'config_style_css'),
        (web_dir / 'config.js', 'config_js'),
    ]

    # Check if all files exist
    for filepath, _ in files:
        if not filepath.exists():
            print(f'Error: File not found: {filepath}')
            sys.exit(1)

    # Generate header
    print('Embedding web assets...')
    print('=' * 60)
    generate_header(files, output_file)
    print('=' * 60)
    print('Done! Web assets embedded successfully.')
    print(f'\nInclude in your code with: #include "web_assets.h"')


if __name__ == '__main__':
    main()
